#!/usr/bin/bash

Executable="jons-slicer"
Jons_Slicer_Core_Source=(
    "main.cpp"
    
    "util/file/file.cpp"
)

function build_lib3mf(){
    local repo_root_dir=$(pwd)
    
    cd lib/lib3mf/
    git submodule update --init --recursive --force # recursive is not necessary at time of writing. Doesn't need to be conditional because it does nothing if it's already initialized. --force makes sure we're on coherent commits.
    cd cmake
    bash ./GenerateMake.sh
    cd ../build/
    make
    
    cd $repo_root_dir
    return 
}

function build_clipper2(){
    local repo_root_dir=$(pwd)
    
    cd lib/Clipper2/
    git submodule update --init --recursive --force # Don't think there are any, but there is a .gitmodules file.
    mkdir build
    cd build
    cmake ../CPP # -DBUILD_SHARED_LIBS=ON # uncomment to make shared library instead.
    cmake --build . --config Release
    
    cd $repo_root_dir
    return
}

# TODO Add auto detection of host OS.
# Expectation of build environment is that zig c++ & some variation of bash are available. This can work on windows if you install zig & git bash.
OS="lin"

while test $# -gt 0; do
    case $1 in
        "--OS")
            OS="$2";
            shift 2;
        ;;
    esac
    case $1 in
        "--build-deps")
            build_lib3mf;
            build_clipper2;
            shift 1;
        ;;
    esac
done

if [[ $OS != "lin" && $OS != "win" ]]; then
    echo "Provided invalid OS option: '${OS}'"
    echo "Valid options:"
    echo "    lin"
    echo "    win"
    #echo "    mac" # should support but I don't have access to a mac. I'm open to other operating systems, but will wait for actual requests.
    exit -1
fi

if [[ $OS == "lin" ]]; then
    TRIPLE=""
    RPATH="-Wl,-rpath=\"\\\$ORIGIN\"" # I can't remember why this is here. I remember it was something awful. # Ringadingding! It's for runtime look up of dlls. By default there may be NO path to search for a DLL, so it can fail to find one right next to the executable. It shouldn't affect a dev machine, but may affect deployments if not present/defined.
    COMPILER="zig c++"
    SYSTEM_INCLUDES="-Ilib/lib3mf/Autogenerated/Bindings/Cpp"
    LINK_DIRS="-Llib/lib3mf/build" #"-L/usr/local/lib"
    LINK_LIBS="-l3mf"
fi

if [[ $OS == "win" ]]; then
    Executable="${Executable}.exe"
    RPATH=""
    COMPILER="zig c++"
fi


# Required variables/parameters name, source files, exe or library (static or shared)
function build(){
    
    local Name="$1"
    local -n Source_Files=$2
    
    
    
    local Object_Files=()
    
    mkdir -p obj
    for file in "${Source_Files[@]}" ; do
        
        if [[ $file =~ [[:space:]]+ ]] ; then
            echo "File path: \"$file\" Contains a space and should not. Build script does not support spaces in paths. Bash handles that poorly."
            exit 1
        fi
        
        object_file="obj/src/$(echo $file | sed -e 's/\.cpp/\.o/')"
        file="src/$file"
        
        path="$(dirname $file)"
        Object_Files+=( "${object_file}" )
        mkdir -p "obj/$path" # otherwise clang++/g++ complain about non-existing directory
        $COMPILER $TRIPLE "$file" -o "${object_file}" -std=c++20 -O0 -c -Isrc $SYSTEM_INCLUDES
    done
    
    
    
    # link files into one executable
    for object in "${Object_Files[@]}" ; do
        file_glob+=" $object"
    done
    
    mkdir -p gen/
    $COMPILER $TRIPLE $LINK_ARGS $file_glob -o "gen/${Name}" $LINK_DIRS $LINK_LIBS
}


build "$Executable" Jons_Slicer_Core_Source




