#!/usr/bin/bash

Jons_Slicer_Core_Source=(
    "math/math.cpp" "math/geom.cpp"
    "util/file/file.cpp"
)

Test_Source=(
    "test/main.cpp"
    "test/test.cpp"
)

# Yes, there's some common logic between building these libraries, but the pathing changes a little and it's not worth having some generic path processing IMO. ( cmake args also fluctuate)
function build_lib3mf(){
    local repo_root_dir=$(pwd)
    
    cd lib/lib3mf/
    git submodule update --init --recursive --force # recursive is not necessary at time of writing. Doesn't need to be conditional because it does nothing if it's already initialized. --force makes sure we're on coherent commits.
    cd cmake
    bash ./GenerateMake.sh -DLIB3MF_TESTS=OFF
    cd ../build/
    make
    
    cd $repo_root_dir
    return 
}

function build_clipper2(){
    local repo_root_dir=$(pwd)
    
    cd lib/Clipper2/
    git submodule update --init --recursive --force # Don't think there are any, but there is a .gitmodules file.
    cd CPP
    mkdir build
    cd build
    cmake .. -DCLIPPER2_TESTS=OFF -DCLIPPER2_EXAMPLES=OFF # -DBUILD_SHARED_LIBS=ON # uncomment to make shared library instead.
    cmake --build . --config Release
    
    cd $repo_root_dir
    return
}

# TODO Add auto detection of host OS. May be able to use uname for OS detection. Don't want to pursue just yet though.
# Expectation of build environment is that zig c++ & some variation of bash are available. This can work on windows if you install zig & git bash.
OS="lin"

while test $# -gt 0; do
    case $1 in
        "--OS")
            OS="$2";
            shift 2;
        ;;
        "--build-deps")
            build_lib3mf;
            build_clipper2;
            shift 1;
        ;;
        "--build-tests")
            BUILD_TESTS="TRUE"
            shift 1;
        ;;
        *)
            echo "Bad argument '$1' given."
            echo "Exiting."
            exit
        ;;
    esac
done

if [[ $OS != "lin" && $OS != "win" ]]; then
    echo "Provided invalid OS option: '${OS}'"
    echo "Valid options:"
    echo "    lin"
    echo "    win"
    #echo "    mac" # should support but I don't have access to a mac. I'm open to other operating systems, but will wait for actual requests.
    exit -1
fi

case "$OS" in
    "lin")
        TRIPLE=""
        RPATH="-Wl,-rpath=\"\\\$ORIGIN\"" # This defines runtime look up of dlls. By default there may be NO path to search for a DLL, so it can fail to find one right next to the executable. It may not affect dev machines, but will affect deployments if not present/defined.
        COMPILER="zig c++"
        GLOBAL_INCLUDES="-Ilib/lib3mf/Autogenerated/Bindings/Cpp"
        GLOBAL_LINK_DIRS="-Llib/lib3mf/build" #"-L/usr/local/lib"
        GLOBAL_LINK_LIBS="-l3mf"
    ;;
    "win")
        COMPILER="zig c++"
    ;;
esac


# Required variables/parameters name, source files, exe or library (static or shared)
function build(){
    
    local Name="$1"
    local -n Source_Files=$2
    local BINARY_TYPE="EXECUTABLE"
    local INCLUDE_DIRS="$GLOBAL_INCLUDES"
    local LINK_DIRS="$GLOBAL_LINK_DIRS"
    local LINK_LIBS="$GLOBAL_LINK_LIBS"
    shift 2;
    
    while test $# -gt 0; do
        case $1 in
            "EXECUTABLE"|"SHARED"|"STATIC")
                BINARY_TYPE="$1";
                if [[ "$BINARY_TYPE" == "STATIC" || "$BINARY_TYPE" == "SHARED" ]]; then
                    COMPILE_ARGS="-fPIC"
                fi
                shift 1;
            ;;
            "LINK_DIR")
                LINK_DIRS="$LINK_DIRS $2";
                shift 2;
            ;;
            "LINK")
                LINK_LIBS="$LINK_LIBS $2";
                shift 2;
            ;;
            *)
                echo "Invalid argument given to build command '$1'."
                echo "Exiting."
                exit
            ;;
        esac
    done
    
    local Object_Files=()
    
    mkdir -p obj
    for file in "${Source_Files[@]}" ; do
        
        if [[ $file =~ [[:space:]]+ ]] ; then
            echo "File path: \"$file\" Contains a space and should not. Build script does not support spaces in paths. Bash handles that poorly."
            exit 1
        fi
        
        local object_file="obj/src/$(echo $file | sed -e 's/\.cpp/\.o/')"
        file="src/$file"
        
        local path="$(dirname $file)"
        Object_Files+=( "${object_file}" )
        mkdir -p "obj/$path" # otherwise clang++/g++ complain about non-existing directory
        zig c++ "$file" -o "${object_file}" -std=c++20 -O0 -c $COMPILE_ARGS -fno-fast-math -Isrc $INCLUDE_DIRS
    done
    
    
    
    # link files into one executable
    local file_glob=""
    for object in "${Object_Files[@]}" ; do
        file_glob+=" $object"
    done
    
    mkdir -p gen/
    case $BINARY_TYPE in
        "EXECUTABLE"|"SHARED")
            zig c++ $file_glob -o "gen/${Name}" $LINK_DIRS $LINK_LIBS
            ;;
        "STATIC")
            ar rcs gen/${Name}.a $file_glob
            ;;
        *)
            echo "Incorrect link type given to 'build' function"
            exit
            ;;
    esac
    
}

build "libjons-slicer" Jons_Slicer_Core_Source STATIC

if [[ -n "$BUILD_TESTS" ]]; then
    build "test" Test_Source EXECUTABLE LINK "-ljons-slicer" LINK_DIR "-Lgen"
fi

