#!/usr/bin/bash

Jons_Slicer_Core_Source=(
    "math/math.cpp" "math/geom.cpp"
    "util/file/file.cpp"
)

Test_Source=(
    "test/main.cpp"
    "test/test.cpp"
)

# Yes, there's some common logic between building these libraries, but the pathing changes a little and it's not worth having some generic path processing IMO. ( cmake args also fluctuate)
function build_lib3mf(){
    local repo_root_dir=$(pwd)
    
    cd lib/lib3mf/
    git submodule update --init --recursive --force # recursive is not necessary at time of writing. Doesn't need to be conditional because it does nothing if it's already initialized. --force makes sure we're on coherent commits.
    cd cmake
    bash ./GenerateMake.sh -DLIB3MF_TESTS=OFF
    cd ../build/
    make
    
    cd $repo_root_dir
    return 
}

function build_clipper2(){
    local repo_root_dir=$(pwd)
    
    cd lib/Clipper2/
    git submodule update --init --recursive --force # Don't think there are any, but there is a .gitmodules file.
    cd CPP
    mkdir build
    cd build
    cmake .. -DCLIPPER2_TESTS=OFF -DCLIPPER2_EXAMPLES=OFF # -DBUILD_SHARED_LIBS=ON # uncomment to make shared library instead.
    cmake --build . --config Release
    
    cd $repo_root_dir
    return
}

# TODO Add auto detection of host OS. May be able to use uname for OS detection. Don't want to pursue just yet though.
# Expectation of build environment is that zig c++ & some variation of bash are available. This can work on windows if you install zig & git bash.
OS="lin"

while test $# -gt 0; do
    case $1 in
        "--OS")
            OS="$2";
            shift 2;
        ;;
        "--build-deps")
            build_lib3mf;
            build_clipper2;
            shift 1;
        ;;
        "--build-tests")
            BUILD_TESTS="TRUE"
            shift 1;
        ;;
        *)
            echo "Bad argument '$1' given."
            echo "Exiting."
            exit
        ;;
    esac
done

if [[ $OS != "lin" && $OS != "win" ]]; then
    echo "Provided invalid OS option: '${OS}'"
    echo "Valid options:"
    echo "    lin"
    echo "    win"
    #echo "    mac" # should support but I don't have access to a mac. I'm open to other operating systems, but will wait for actual requests.
    exit -1
fi

case "$OS" in
    "lin")
        TRIPLE=""
        RPATH="-Wl,-rpath=\"\\\$ORIGIN\"" # This defines runtime look up of dlls. By default there may be NO path to search for a DLL, so it can fail to find one right next to the executable. It may not affect dev machines, but will affect deployments if not present/defined.
        COMPILER="zig c++"
        GLOBAL_INCLUDES="-Ilib/lib3mf/Autogenerated/Bindings/Cpp"
        GLOBAL_LINK_DIRS="-Llib/lib3mf/build" #"-L/usr/local/lib"
        GLOBAL_LINK_LIBS="-l3mf"
    ;;
    "win")
        COMPILER="zig c++"
    ;;
esac


# Parameters
#   $1 = end binary name. REQUIRED
#   $2 = name of array holding the source files. REQUIRED
#
# All other parameters are non-positional. They must come after the first 2 & are optional
#
#   ("EXECUTABLE"|"SHARED"|"STATIC") describes the type of binary to be built. Takes no arguments.
#   "LINK_DIR" adds a link directory. Takes one argument, the link directory. Be mindful of spaces in paths.
#   "LINK" adds a library to be linked. Takes one argument, the library.
function build(){
    
    local Name="$1"
    local -n Source_Files=$2
    local BINARY_TYPE="EXECUTABLE"
    local INCLUDE_DIRS="$GLOBAL_INCLUDES"
    local LINK_DIRS="" #"$GLOBAL_LINK_DIRS"
    local LINK_DIRS_ARR=()
    local LINK_LIBS="" #"$GLOBAL_LINK_LIBS"
    local LINK_LIBS_ARR=()
    shift 2;
    
    while test $# -gt 0; do
        case $1 in
            "EXECUTABLE"|"SHARED"|"STATIC")
                BINARY_TYPE="$1";
                if [[ "$BINARY_TYPE" == "STATIC" || "$BINARY_TYPE" == "SHARED" ]]; then
                    COMPILE_ARGS="-fPIC"
                fi
                shift 1;
            ;;
            "LINK_DIR")
                LINK_DIRS_ARR+=("$2");
                shift 2;
            ;;
            "LINK")
                LINK_LIBS_ARR+=("$2");
                shift 2;
            ;;
            *)
                echo "Invalid argument given to build command '$1'."
                echo "Exiting."
                exit
            ;;
        esac
    done
    
    # Manually dereference library names so I can call my core lib jons-slicer instead of libjons-slicer. 
    for file in "${LINK_LIBS_ARR[@]}" ; do
        for dir in "${LINK_DIRS_ARR[@]}" ; do
            #echo "find \"${dir}\" -name \"${file}*\" -printf '%P\n' | grep \"${file}\\(\\.so\$\\|\\.a\$\\)\""
            local LIB="$(find "${dir}" -name "${file}*" -printf '%P\n' | grep "${file}\\(\\.so\$\\|\\.a\$\\)")" # This will fail if there's both a static & dynamic lib. You could control for that by adding an optional flag to the LINK command which specifies. ( or add a LINK_STATIC & LINK_DYNAMIC
            
            if [[ "${LIB}" != "" ]] ; then
                LINK_LIBS+=" ${NO_SYMLINK}${dir}/${LIB}"
                break   
            fi
            
        done
    done
    
    for dir in "${LINK_DIRS_ARR[@]}" ; do
        LINK_DIRS+=" -L${dir}"
    done
    
    local Object_Files=()
    
    mkdir -p obj
    for file in "${Source_Files[@]}" ; do
        
        if [[ $file =~ [[:space:]]+ ]] ; then
            echo "File path: \"$file\" Contains a space and should not. Build script does not support spaces in paths. Bash handles that poorly."
            exit 1
        fi
        
        local object_file="obj/src/$(echo $file | sed -e 's/\.cpp/\.o/')"
        file="src/$file"
        
        local path="$(dirname $file)"
        Object_Files+=( "${object_file}" )
        mkdir -p "obj/$path" # otherwise clang++/g++ complain about non-existing directory
        zig c++ "$file" -o "${object_file}" -std=c++20 -O0 -c $COMPILE_ARGS -fno-fast-math -Isrc $INCLUDE_DIRS
    done
    
    
    # link files into one executable
    
    local file_glob=""
    for object in "${Object_Files[@]}" ; do
        file_glob+=" $object"
    done
    
    mkdir -p gen/
    case $BINARY_TYPE in
        "EXECUTABLE"|"SHARED")
            #echo "zig c++ $file_glob -o "gen/${Name}" $LINK_DIRS $LINK_LIBS $RPATH"
            zig c++ $file_glob -o "gen/${Name}" $LINK_DIRS $LINK_LIBS $RPATH
            ;;
        "STATIC")
            ar rcs gen/${Name}.a $file_glob
            ;;
        *)
            echo "Incorrect link type given to 'build' function"
            exit
            ;;
    esac
    
}

build "jons-slicer" Jons_Slicer_Core_Source STATIC LINK_DIR lib/lib3mf/build LINK lib3mf
    
if [[ -n "$BUILD_TESTS" ]]; then
    build "test" Test_Source EXECUTABLE LINK jons-slicer LINK_DIR gen LINK_DIR lib/lib3mf/build LINK lib3mf
fi
